title: "My Personal Page"
remote_theme: "d33pk3rn3l/no-style-please"
baseurl: ""
url: "https://d33pk3rn3l.github.io"
markdown: kramdown
theme_config:
  appearance: dark
  link: "#ab009d"
  date_format: false
defaults:
  - scope:
      path: "_assets/images"