title: "My Personal Page"
remote_theme: "d33pk3rn3l/no-style-please"
baseurl: ""
url: "https://d33pk3rn3l.github.io"
markdown: kramdown
theme_config:
  appearance: dark
  link: "#ab009d"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d"
defaults:
  - scope:
      path: "_assets/images"