# Example: https://github.com/riggraz/no-style-please/blob/master/_config.yml

title: "d33pk3rn3l's minimal site"
remote_theme: "d33pk3rn3l/no-style-please"
baseurl: ""
description: "Personal site of d33pk3rn3l with projects, blog posts and more."
url: "https://d33pk3rn3l.github.io"
favicon: "favicon.png"
markdown: kramdown
theme_config:
  appearance: dark
  back_home_text: "<-" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d"
  show_description: false
defaults:
  - scope:
      path: "_assets/images"

sass:
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
